### ISSUE TITLE
How to configure frequency?

### ISSUE THREAD

**Issue by rr326** [m-lab/murakami#10]
I would like to configure the frequency murakami runs. (I use a LTE router and anecdotally it seems to be WILDLY variable in it's performance. I'd like to test it hourly to see if A) it really is variable; B) if it is time based.)

How do I configure Murakami?

**Comment by rr326** [comment]
I looked at the code (run.py in the container) and it looks like this isn't designed to be configured.  (Feature request!)

But if anyone finds this you can create a crontab like the following:
```
# Run a test every hour
0 * * * * docker exec mlab python -c "import run; import logging; logging.getLogger().setLevel(logging.DEBUG);run.do_ndt_test('');  run.summarize_tests()" >> ${HOME}/murakamicrontab.log 2>&1
```

**Comment by pboothe** [comment]
This is a bad idea, and people who do this cause load spikes on our measurement servers, which in turn messes up their (and our) measurements.  Please at least choose a start time besides "on the hour".  Ideally you would use an exponentially distributed random number generator (like https://github.com/m-lab/go/blob/master/memoryless/memoryless.go ) to ensure that the time average of your measurements has the PASTA property - https://en.wikipedia.org/wiki/Arrival_theorem#Theorem_for_arrivals_governed_by_a_Poisson_process

That PASTA advice may be too much, but definitely please don't fire up a test every hour on the hour. It just contributes to spike loads which, when they get severe, can cause measurements to be bad.  Choose a random number between 0 and 59 (inclusive) and put that random number in the crontab instead of zero.

**Comment by rr326** [comment]
@pboothe Thank you for explaining that. I'll use your advice AND only test for a short period.

**Comment by critzo** [comment]
@rr326 @pboothe - murakami is already using a poisson process to run at a random time, I believe twice daily. The frequency can be increased while still randomizing. See the function `perform_test_loop` in `run.py`and code comments.
