### ISSUE TITLE
write a JSON spec for Murakami's dash test runner

### ISSUE THREAD

**Issue by critzo** [m-lab/murakami#32]
Write a specification for the dash client, that is a simple, non-nested, single object JSON file that includes Murakami metadata and test data.

This will be used to add functionality to the ndt5-client-go test runner to produce test output that matches the spec.

**Comment by critzo** [comment]
@robertodauria Here is a spec for Murakami DASH output:
```
{
    "test_name": "dash",
    "uuid": "4364c5da-a07b-4188-9cbd-ad79e5a7c2f8",
    "test_runtime": 33.1672148704529,
    "test_runtime_units": "seconds",
    "test_start_time": "2017-07-24 09:44:53",
    "real_address": "79.40.147.190",
    "probe_asn": "AS1234",
    "probe_cc": "IT",
    "connect_latency": 0.0268912315368652,
    "connect_latency_units": "seconds" 
    "median_bitrate": 5786.0,
    "median_bitrate_units": "Kbit/s",
    "min_playout_delay": 0.214933633804321
    "min_playout_delay_units": "seconds"
}
```

**Comment by robertodauria** [comment]
Same question as with the ndt5/ndt7 clients: how do we report that the test failed?

Also, since we have 100% control over Murakami's output, could we keep the capitalization consistent? e.g. using CamelCase as in the ndt5/7 outputs:
```
{
    "TestName": "dash",
    "TestUUID": "...",
    "TestRuntime": ...,
    [...]
}
```

Another thing that crossed my mind: in the UI sketches for the VIsualization tool there's a "Stream quality" bar chart which should - if I understand correctly - give an indication of stream quality at different bitrates. Would we be able to display that just with the `median_bitrate` in this output? 

Unless there's a technical reason to keep this JSON flat, I wouldn't be opposed to adding sub-objects containing further details for each streaming rate that was tested - not necessarily right now, it could be a later step.

**Comment by critzo** [comment]
@robertodauria I'd suggest we report errors similarly in DASH to the ndt5 and ndt7 clients. We have one or more key:value pairs in the spec for error messages, which are set NULL or no value when there is no error, and have the error if there was one. If there are errors, then other values normally reported should be NULL or no value, except for key test metadata: 
```
{
    "ServerIP": "194.116.85.211",     # "remote_address": "194.116.85.211",
    "ClientIP": "79.40.147.190",        #  "real_address": "79.40.147.190",
    "MurakamiLocation": "<MURAKAMI 'LOCATION' ENV VAR>",
    "MurakamiNetworkType": "<MURAKAMI 'NETWORK_TYPE' ENV VAR>",
    "MurakamiConnectionType": "<MURAKAMI 'CONNECTION_TYPE' ENV VAR>",    
    "TestUUID": "4364c5da-a07b-4188-9cbd-ad79e5a7c2f8",   
    "TestProtocol": "dash",
    "TestError": "NULL",
    "TestRuntime": 33.1672148704529,
    "TestRuntimeUnits": "seconds",
    "TestStartTime": "2017-07-24 09:44:53",
    "ProbeASN": "AS1234",
    "ProbeCC": "IT",
    "ConnectLatency": 0.0268912315368652,
    "ConnectLatencyUnits": "seconds" 
    "MedianBitrate": 5786.0,
    "MedianBitrateUnits": "Kbit/s",
    "MinPlayoutDelay": 0.214933633804321
    "MinPlayoutDelayUnits": "seconds"
}
```

Regarding the reporting of median bitrate and giving an indication of streaming quality, that will be part of the front-end, given that this is how OONI does it, and the values for different levels are fairly static. Tracking those levels and other ways to represent DASH data in #40 

If we can identify the different streaming rates that were tested from the DASH test results, then yes, let's add `key:value` pairs for them. I don't want to add sub-objects. Having a flat object is our preference.
